<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use App\User;
use App\Person;
use App\Hospital;

use Faker\Factory as Faker;

class AdminTableSeeder extends Seeder {

    public function run()
    {
        $faker = Faker::create();

        // User::create(['name' => 'Noel', 'email' => 'noel.logan@gmail.com', 'password' => '123', 'is_superuser' => true]);

		Person::create(['nombre' => 'Carlos Alberto', 'apaterno' => 'Takeshita', 'amaterno' => 'Nishimura', 'full_name' => 'Takeshita Nishimura Carlos Alberto', 'tipo' => 'CEH', 'phone' => '985595985', 'congregacion' => '', 'HLC' => '' , 'email_jw' => 'CTakeshita@jwpub.org', 'is_new' => '', 'ceh_id' => 0, 'ceh2_id' => 0]);
		Person::create(['nombre' => 'Fabricio', 'apaterno' => 'Hinojosa', 'amaterno' => '', 'full_name' => 'Hinojosa Fabricio', 'tipo' => 'CEH', 'phone' => '997930827', 'congregacion' => '', 'HLC' => '' , 'email_jw' => 'FabricioH@jwpub.org', 'email' => '', 'is_new' => '', 'ceh_id' => 0, 'ceh2_id' => 0]);
		Person::create(['nombre' => 'César Guillermo', 'apaterno' => 'Uriarte', 'amaterno' => 'De La Cruz', 'full_name' => 'Uriarte De La Cruz César Guillermo', 'tipo' => 'CEH', 'phone' => '998610426', 'congregacion' => '', 'HLC' => '' , 'email_jw' => 'CesarU3@jwpub.org', 'email' => '', 'is_new' => '', 'ceh_id' => 0, 'ceh2_id' => 0]);
		Person::create(['nombre' => 'Raúl Iván', 'apaterno' => 'Sánchez', 'amaterno' => 'Morán', 'full_name' => 'Sánchez Morán Raúl Iván', 'tipo' => 'CEH', 'phone' => '997272693', 'congregacion' => '', 'HLC' => '' , 'email_jw' => 'SRaulI@jwpub.org', 'email' => '', 'is_new' => '', 'ceh_id' => 0, 'ceh2_id' => 0]);
		Person::create(['nombre' => 'Daniel', 'apaterno' => 'Ruiz', 'amaterno' => 'Lee', 'full_name' => 'Ruiz Lee Daniel', 'tipo' => 'CEH', 'phone' => '981535287', 'congregacion' => '', 'HLC' => '' , 'email_jw' => 'DanielRuizLee@jwpub.org', 'email' => '', 'is_new' => '', 'ceh_id' => 0, 'ceh2_id' => 0]);
		Person::create(['nombre' => 'Marco Aurelio', 'apaterno' => 'Rosado', 'amaterno' => 'Balarezo', 'full_name' => 'Rosado Balarezo Marco Aurelio', 'tipo' => 'CEH', 'phone' => '966520261', 'congregacion' => '', 'HLC' => '' , 'email_jw' => 'MarcoRosado@jwpub.org', 'email' => '', 'is_new' => '', 'ceh_id' => 0, 'ceh2_id' => 0]);
		Person::create(['nombre' => 'José Gerson', 'apaterno' => 'Plasencia', 'amaterno' => 'Carrascal', 'full_name' => 'Plasencia Carrascal José Gerson', 'tipo' => 'CEH', 'phone' => '988243506', 'congregacion' => '', 'HLC' => '' , 'email_jw' => 'JPlasencia@jwpub.org', 'email' => '', 'is_new' => '', 'ceh_id' => 0, 'ceh2_id' => 0]);
		Person::create(['nombre' => 'Efrain Vicente', 'apaterno' => 'Pahuara', 'amaterno' => 'Delao', 'full_name' => 'Pahuara Delao Efrain Vicente', 'tipo' => 'CEH', 'phone' => '998127368', 'congregacion' => '', 'HLC' => '' , 'email_jw' => 'Efrainp11@jwpub.org', 'email' => '', 'is_new' => '', 'ceh_id' => 0, 'ceh2_id' => 0]);
		Person::create(['nombre' => 'Henry Feliciano', 'apaterno' => 'Ortíz', 'amaterno' => 'Bello', 'full_name' => 'Ortíz Bello Henry Feliciano', 'tipo' => 'CEH', 'phone' => '990413178', 'congregacion' => '', 'HLC' => '' , 'email_jw' => 'HenryFO15@jwpub.org', 'email' => '', 'is_new' => '', 'ceh_id' => 0, 'ceh2_id' => 0]);
		Person::create(['nombre' => 'Segundo Reynaldo', 'apaterno' => 'Olano', 'amaterno' => 'Montenegro', 'full_name' => 'Olano Montenegro Segundo Reynaldo', 'tipo' => 'CEH', 'phone' => '998874236', 'congregacion' => '', 'HLC' => '' , 'email_jw' => '3OlanoSegundo@jwpub.org', 'email' => '', 'is_new' => '', 'ceh_id' => 0, 'ceh2_id' => 0]);
		Person::create(['nombre' => 'Omar Alexis', 'apaterno' => 'Nieva', 'amaterno' => 'Calderon', 'full_name' => 'Nieva Calderon Omar Alexis', 'tipo' => 'CEH', 'phone' => '993415123', 'congregacion' => '', 'HLC' => '' , 'email_jw' => 'OmarNieva17@jwpub.org', 'email' => '', 'is_new' => '', 'ceh_id' => 0, 'ceh2_id' => 0]);
		Person::create(['nombre' => 'Rider Alberto', 'apaterno' => 'Navarro', 'amaterno' => 'Vignatti', 'full_name' => 'Navarro Vignatti Rider Alberto', 'tipo' => 'CEH', 'phone' => '999142005', 'congregacion' => '', 'HLC' => '' , 'email_jw' => 'RiderN33@jwpub.org', 'email' => '', 'is_new' => '', 'ceh_id' => 0, 'ceh2_id' => 0]);
		Person::create(['nombre' => 'Milder Jesús', 'apaterno' => 'Nacimiento', 'amaterno' => 'Maldonado', 'full_name' => 'Nacimiento Maldonado Milder Jesús', 'tipo' => 'CEH', 'phone' => '999445078', 'congregacion' => '', 'HLC' => '' , 'email_jw' => 'MilderNacimiento33@jwpub.org', 'email' => '', 'is_new' => '', 'ceh_id' => 0, 'ceh2_id' => 0]);
		Person::create(['nombre' => 'Italo Mario', 'apaterno' => 'Medina', 'amaterno' => 'Olórtegui', 'full_name' => 'Medina Olórtegui Italo Mario', 'tipo' => 'CEH', 'phone' => '961567099', 'congregacion' => '', 'HLC' => '' , 'email_jw' => 'ItaloM4@jwpub.org', 'email' => '', 'is_new' => '', 'ceh_id' => 0, 'ceh2_id' => 0]);
		Person::create(['nombre' => 'Miguel Angel', 'apaterno' => 'Malpartida', 'amaterno' => 'Cristóbal', 'full_name' => 'Malpartida Cristóbal Miguel Angel', 'tipo' => 'CEH', 'phone' => '966631942', 'congregacion' => '', 'HLC' => '' , 'email_jw' => 'MMalpartida10@jwpub.org', 'email' => '', 'is_new' => '', 'ceh_id' => 0, 'ceh2_id' => 0]);
		Person::create(['nombre' => 'Pedro Alonso', 'apaterno' => 'Loarte', 'amaterno' => 'Obregón', 'full_name' => 'Loarte Obregón Pedro Alonso', 'tipo' => 'CEH', 'phone' => '926257686', 'congregacion' => '', 'HLC' => '' , 'email_jw' => 'PedroLoarte@jwpub.org', 'email' => '', 'is_new' => '', 'ceh_id' => 0, 'ceh2_id' => 0]);
		Person::create(['nombre' => 'Jonatan Hubert', 'apaterno' => 'Lliuya', 'amaterno' => 'Chauca', 'full_name' => 'Lliuya Chauca Jonatan Hubert', 'tipo' => 'CEH', 'phone' => '933872096', 'congregacion' => '', 'HLC' => '' , 'email_jw' => 'JLliuya@jwpub.org', 'email' => '', 'is_new' => '', 'ceh_id' => 0, 'ceh2_id' => 0]);
		Person::create(['nombre' => 'Jaime Daniel', 'apaterno' => 'Levano', 'amaterno' => 'Pasache', 'full_name' => 'Levano Pasache Jaime Daniel', 'tipo' => 'CEH', 'phone' => '982756891', 'congregacion' => '', 'HLC' => '' , 'email_jw' => 'DanielL33@jwpub.org', 'email' => '', 'is_new' => '', 'ceh_id' => 0, 'ceh2_id' => 0]);
		Person::create(['nombre' => 'César Mario', 'apaterno' => 'Kamimoto', 'amaterno' => 'Rodríguez', 'full_name' => 'Kamimoto Rodríguez César Mario', 'tipo' => 'CEH', 'phone' => '995821786', 'congregacion' => '', 'HLC' => '' , 'email_jw' => 'CeMario@jwpub.org', 'email' => '', 'is_new' => '', 'ceh_id' => 0, 'ceh2_id' => 0]);
		Person::create(['nombre' => 'Amadeo Oscar', 'apaterno' => 'Jimenez', 'amaterno' => 'Pajuelo', 'full_name' => 'Jimenez Pajuelo Amadeo Oscar', 'tipo' => 'CEH', 'phone' => '969486832', 'congregacion' => '', 'HLC' => '' , 'email_jw' => 'OscarJ39@jwpub.org', 'email' => '', 'is_new' => '', 'ceh_id' => 0, 'ceh2_id' => 0]);
		Person::create(['nombre' => 'Pedro', 'apaterno' => 'Gutierrez', 'amaterno' => 'Huaman', 'full_name' => 'Gutierrez Huaman Pedro', 'tipo' => 'CEH', 'phone' => '945378855', 'congregacion' => '', 'HLC' => '' , 'email_jw' => 'ParaisoPedroG@jwpub.org', 'email' => '', 'is_new' => '', 'ceh_id' => 0, 'ceh2_id' => 0]);
		Person::create(['nombre' => 'Andrés', 'apaterno' => 'García', 'amaterno' => '', 'full_name' => 'García  Andrés', 'tipo' => 'CEH', 'phone' => '959567794', 'congregacion' => '', 'HLC' => '' , 'email_jw' => '4GAndres@jwpub.org', 'email' => '', 'is_new' => '', 'ceh_id' => 0, 'ceh2_id' => 0]);
		Person::create(['nombre' => 'Felix Arturo', 'apaterno' => 'Chancafe', 'amaterno' => 'Ocros', 'full_name' => 'Chancafe Ocros Felix Arturo', 'tipo' => 'CEH', 'phone' => '996287337', 'congregacion' => '', 'HLC' => '' , 'email_jw' => 'ACHANCAFE3@jwpub.org', 'email' => '', 'is_new' => '', 'ceh_id' => 0, 'ceh2_id' => 0]);
		Person::create(['nombre' => 'Karim Martín', 'apaterno' => 'Cajacuri', 'amaterno' => 'Nuñez', 'full_name' => 'Cajacuri Nuñez Karim Martín', 'tipo' => 'CEH', 'phone' => '990894889', 'congregacion' => '', 'HLC' => '' , 'email_jw' => 'CajacuriK8@jwpub.org', 'email' => '', 'is_new' => '', 'ceh_id' => 0, 'ceh2_id' => 0]);
		Person::create(['nombre' => 'Eusebio', 'apaterno' => 'Cacñahuaray', 'amaterno' => 'Huillcahuari', 'full_name' => 'Cacñahuaray Huillcahuari Eusebio', 'tipo' => 'CEH', 'phone' => '995523935', 'congregacion' => '', 'HLC' => '' , 'email_jw' => 'EusebioC12@jwpub.org', 'email' => '', 'is_new' => '', 'ceh_id' => 0, 'ceh2_id' => 0]);
		Person::create(['nombre' => 'Jhonathan', 'apaterno' => 'Blanco', 'amaterno' => 'Elera', 'full_name' => 'Blanco Elera Jhonathan', 'tipo' => 'CEH', 'phone' => '945422577', 'congregacion' => '', 'HLC' => '' , 'email_jw' => 'JBlancoEler18@jwpub.org', 'email' => '', 'is_new' => '', 'ceh_id' => 0, 'ceh2_id' => 0]);
		Person::create(['nombre' => 'Héctor Fernando', 'apaterno' => 'Ayala', 'amaterno' => 'Huerta', 'full_name' => 'Ayala Huerta Héctor Fernando', 'tipo' => 'CEH', 'phone' => '990078953', 'congregacion' => '', 'HLC' => '' , 'email_jw' => '9AHector@jwpub.org', 'email' => '', 'is_new' => '', 'ceh_id' => 0, 'ceh2_id' => 0]);
		Person::create(['nombre' => 'Miguel Angel', 'apaterno' => 'Alarcón', 'amaterno' => 'Luque', 'full_name' => 'Alarcón Luque Miguel Angel', 'tipo' => 'CEH', 'phone' => '956529681', 'congregacion' => '', 'HLC' => '' , 'email_jw' => 'MAlarconLuq19@jwpub.org', 'email' => '', 'is_new' => '', 'ceh_id' => 0, 'ceh2_id' => 0]);
		Person::create(['nombre' => 'Omar Ricardo Jesús', 'apaterno' => 'Alcazar', 'amaterno' => 'Ramos', 'full_name' => 'Alcazar Ramos Omar Ricardo Jesús', 'tipo' => 'GVP', 'phone' => '932048916 ; 012489804', 'congregacion' => '(15172) MARIATEGUI - VILLA EL SALVADOR LIM', 'HLC' => 'LIM-27' , 'email_jw' => 'OmarAlcazarRam20@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 24, 'ceh2_id' => 11]);
		Person::create(['nombre' => 'Ricardo Israel', 'apaterno' => 'Aguirre', 'amaterno' => 'Osorio', 'full_name' => 'Aguirre Osorio Ricardo Israel', 'tipo' => 'GVP', 'phone' => '959346853 ; 015288870', 'congregacion' => '(737) VILLA DEL NORTE - LOS OLIVOS LIM', 'HLC' => 'LIM-07' , 'email_jw' => '12ARicardo@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 27, 'ceh2_id' => 27]);
		Person::create(['nombre' => 'David', 'apaterno' => 'Aliaga', 'amaterno' => 'Sánchez', 'full_name' => 'Aliaga Sánchez David', 'tipo' => 'GVP', 'phone' => '956798135 ; 013761931', 'congregacion' => '(8136) FLORES OESTE - SAN JUAN DE LURIGANCHO LIM', 'HLC' => 'LIM-16' , 'email_jw' => '41DAliaga@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 15, 'ceh2_id' => 15]);
		Person::create(['nombre' => 'Italo Miguel ', 'apaterno' => 'Agüero', 'amaterno' => 'Palacin', 'full_name' => 'Agüero Palacin Italo Miguel ', 'tipo' => 'GVP', 'phone' => '998702179', 'congregacion' => '(15242) LA CALERA - SURQUILLO LIM ', 'HLC' => 'LIM-19' , 'email_jw' => '20AgueroPalaI@jwpub.org ; Imap587@hotmail.com', 'email' => '', 'is_new' => 'A', 'ceh_id' => 1, 'ceh2_id' => 4]);
		Person::create(['nombre' => 'David Asunción', 'apaterno' => 'Aramburú', 'amaterno' => 'Zavaleta', 'full_name' => 'Aramburú Zavaleta David Asunción', 'tipo' => 'GVP', 'phone' => '947281044 ; 012833814', 'congregacion' => '(15594) LATINOAMERICA - VILLA MARIA DEL TRIUNFO LIM', 'HLC' => 'LIM-23' , 'email_jw' => 'ARAMBURUD13@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 10, 'ceh2_id' => 24]);
		Person::create(['nombre' => 'Víctor Humberto', 'apaterno' => 'Aranzana', 'amaterno' => 'Allende', 'full_name' => 'Aranzana Allende Víctor Humberto', 'tipo' => 'GVP', 'phone' => '949632796', 'congregacion' => '(1875) HONOR Y LEALTAD - SANTIAGO DE SURCO LIM', 'HLC' => 'LIM-25' , 'email_jw' => '3avictorh@jwpub.org; victoraranzana34@gmail.com', 'email' => '', 'is_new' => 'A', 'ceh_id' => 5, 'ceh2_id' => 1]);
		Person::create(['nombre' => 'Ricardo Augusto', 'apaterno' => 'Arriarán', 'amaterno' => 'García', 'full_name' => 'Arriarán García Ricardo Augusto', 'tipo' => 'GVP', 'phone' => '989549219', 'congregacion' => '(18) ANCIETA - EL AGUSTINO LIM', 'HLC' => 'LIM-17' , 'email_jw' => 'augusto_tj@hotmail.com ; ARicardo5@jwpub.org', 'email' => '', 'is_new' => 'A', 'ceh_id' => 18, 'ceh2_id' => 25]);
		Person::create(['nombre' => 'Esteban Alexander', 'apaterno' => 'Asmat', 'amaterno' => 'Burgos', 'full_name' => 'Asmat Burgos Esteban Alexander', 'tipo' => 'GVP', 'phone' => '991041266 ; 012211356', 'congregacion' => '(15019) LARCO DE MIRAFLORES - MIRAFLORES LIM', 'HLC' => 'LIM-20' , 'email_jw' => 'AlexanderAsmat21@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 14, 'ceh2_id' => 1]);
		Person::create(['nombre' => 'Hugo Berardo', 'apaterno' => 'Barba', 'amaterno' => 'Vara', 'full_name' => 'Barba Vara Hugo Berardo', 'tipo' => 'GVP', 'phone' => '996112135', 'congregacion' => '(1008) SANTA ANITA - LIM', 'HLC' => 'LIM-18' , 'email_jw' => 'HugoBarbaVara13@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 22, 'ceh2_id' => 23]);
		Person::create(['nombre' => 'Jackson Alex', 'apaterno' => 'Barboza', 'amaterno' => 'Celedonio', 'full_name' => 'Barboza Celedonio Jackson Alex', 'tipo' => 'GVP', 'phone' => '946529975', 'congregacion' => '(15644) PRADERAS - SANTA ANITA LIM', 'HLC' => 'LIM-18' , 'email_jw' => 'JacksonB1@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 25, 'ceh2_id' => 0]);
		Person::create(['nombre' => 'Elder Augusto', 'apaterno' => 'Barrantes', 'amaterno' => 'Rios', 'full_name' => 'Barrantes Rios Elder Augusto', 'tipo' => 'GVP', 'phone' => '948875104', 'congregacion' => '(15461) LAS TORRES - SAN JUAN DE MIRAFLORES LIM', 'HLC' => 'LIM-24' , 'email_jw' => 'Ebarrantes@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 10, 'ceh2_id' => 24]);
		Person::create(['nombre' => 'Guillermo Emilio', 'apaterno' => 'Becerra', 'amaterno' => 'Montesinos', 'full_name' => 'Becerra Montesinos Guillermo Emilio', 'tipo' => 'GVP', 'phone' => '997843348 ; 015708697', 'congregacion' => '(15172) MARIATEGUI - VILLA EL SALVADOR LIM', 'HLC' => 'LIM-27' , 'email_jw' => 'BecerraGuillermo@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 24, 'ceh2_id' => 11]);
		Person::create(['nombre' => 'José Martín', 'apaterno' => 'Buendía', 'amaterno' => 'Cubas', 'full_name' => 'Buendía Cubas José Martín', 'tipo' => 'GVP', 'phone' => '968207693', 'congregacion' => '(1222) ZARUMILLA - SAN MARTIN DE PORRES LIM', 'HLC' => 'LIM-12' , 'email_jw' => 'BuendiaJ29@jwpub.org', 'email' => '', 'is_new' => 'A', 'ceh_id' => 6, 'ceh2_id' => 3]);
		Person::create(['nombre' => 'Jorge Luis', 'apaterno' => 'Cabanillas', 'amaterno' => 'Samán', 'full_name' => 'Cabanillas Samán Jorge Luis', 'tipo' => 'GVP', 'phone' => '988843631 ; 016580926', 'congregacion' => '(8953) JAMAICA - COMAS LIM', 'HLC' => 'LIM-05' , 'email_jw' => 'JorgeCabanillas25@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 16, 'ceh2_id' => 16]);
		Person::create(['nombre' => 'Luis Angel', 'apaterno' => 'Calderón', 'amaterno' => 'Mejía', 'full_name' => 'Calderón Mejía Luis Angel', 'tipo' => 'GVP', 'phone' => '979344889', 'congregacion' => '(661) MARANGA - SAN MIGUEL LIM', 'HLC' => 'LIM-10' , 'email_jw' => 'LuisCalderonMe32@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 13, 'ceh2_id' => 13]);
		Person::create(['nombre' => 'Percy Edwin', 'apaterno' => 'Campos', 'amaterno' => 'Palomino', 'full_name' => 'Campos Palomino Percy Edwin', 'tipo' => 'GVP', 'phone' => '933838488 ; 016051515', 'congregacion' => '(1057) TABLADA - VILLA MARIA DEL TRIUNFO LIM', 'HLC' => 'LIM-27' , 'email_jw' => 'CPercy@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 17, 'ceh2_id' => 11]);
		Person::create(['nombre' => 'Juan José ', 'apaterno' => 'Cano', 'amaterno' => 'Ruiz', 'full_name' => 'Cano Ruiz Juan José ', 'tipo' => 'GVP', 'phone' => '943293256', 'congregacion' => '(15529) ALAMEDA CANTA - SAN MARTIN DE PORRES LIM', 'HLC' => 'LIM-12' , 'email_jw' => 'JJCanoRuiz@jwpub.org , computecj@hotmail.com', 'email' => '', 'is_new' => 'A', 'ceh_id' => 3, 'ceh2_id' => 21]);
		Person::create(['nombre' => 'Ramsés Santos', 'apaterno' => 'Cárdenas', 'amaterno' => 'del Pino', 'full_name' => 'Cárdenas del Pino Ramsés Santos', 'tipo' => 'GVP', 'phone' => '934673789; 012390145', 'congregacion' => '(14840) FLORES ESTE - SAN JUAN DE LURIGANCHO LIM', 'HLC' => 'LIM-13' , 'email_jw' => 'RansesC1@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 15, 'ceh2_id' => 15]);
		Person::create(['nombre' => 'Rubén Darío', 'apaterno' => 'Cárdenas', 'amaterno' => 'Vera', 'full_name' => 'Cárdenas Vera Rubén Darío', 'tipo' => 'GVP', 'phone' => '929904659; 013838787', 'congregacion' => '(15909) LAS BRISAS - VILLA EL SALVADOR LIM', 'HLC' => 'LIM-27' , 'email_jw' => '26CRuben@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 17, 'ceh2_id' => 11]);
		Person::create(['nombre' => 'Arnaldo', 'apaterno' => 'Carmona', 'amaterno' => 'Velásquez', 'full_name' => 'Carmona Velásquez Arnaldo', 'tipo' => 'GVP', 'phone' => '998148673 ; 998148673', 'congregacion' => '(15917) PUERTA DE PRO - LOS OLIVOS LIM', 'HLC' => 'LIM-02' , 'email_jw' => 'ArnaldoCarmonaVel@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 16, 'ceh2_id' => 16]);
		Person::create(['nombre' => 'Ismael', 'apaterno' => 'Carranza', 'amaterno' => 'Quispe', 'full_name' => 'Carranza Quispe Ismael', 'tipo' => 'GVP', 'phone' => '996050251; 992443569', 'congregacion' => '(16022) LAS VIÑAS - PUENTE PIEDRA LIM', 'HLC' => 'LIM-01' , 'email_jw' => 'IsmaelC16@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 16, 'ceh2_id' => 16]);
		Person::create(['nombre' => 'Josué Samuel', 'apaterno' => 'Carrasco', 'amaterno' => 'Carbajal', 'full_name' => 'Carrasco Carbajal Josué Samuel', 'tipo' => 'GVP', 'phone' => '936777668; 014932376', 'congregacion' => '(15256) 24 DE JUNIO - VILLA EL SALVADOR LIM', 'HLC' => 'LIM-27' , 'email_jw' => '1CarrascoCaJ@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 24, 'ceh2_id' => 11]);
		Person::create(['nombre' => 'Federico', 'apaterno' => 'Carrera', 'amaterno' => 'Fernandez', 'full_name' => 'Carrera Fernandez Federico', 'tipo' => 'GVP', 'phone' => '996660939', 'congregacion' => '(570) EMANCIPACION - LIMA LIM ', 'HLC' => 'LIM-11' , 'email_jw' => 'FCarrera9@jwpub.org', 'email' => '', 'is_new' => 'A', 'ceh_id' => 7, 'ceh2_id' => 6]);
		Person::create(['nombre' => 'Ernesto Wladimir', 'apaterno' => 'Castilla', 'amaterno' => 'García', 'full_name' => 'Castilla García Ernesto Wladimir', 'tipo' => 'GVP', 'phone' => '993734532', 'congregacion' => '(1438) VITARTE - LIM', 'HLC' => 'LIM-22' , 'email_jw' => '24CErnesto@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 25, 'ceh2_id' => 0]);
		Person::create(['nombre' => 'Rosalio', 'apaterno' => 'Ccahuana', 'amaterno' => 'Damián', 'full_name' => 'Ccahuana Damián Rosalio', 'tipo' => 'GVP', 'phone' => '998658378; 017663575', 'congregacion' => '(15909) LAS BRISAS - VILLA EL SALVADOR LIM', 'HLC' => 'LIM-27' , 'email_jw' => 'RosalioCahuana@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 17, 'ceh2_id' => 11]);
		Person::create(['nombre' => 'Emerson', 'apaterno' => 'Ccoya', 'amaterno' => 'Incarroca', 'full_name' => 'Ccoya Incarroca Emerson', 'tipo' => 'GVP', 'phone' => '988523873', 'congregacion' => '(1859) PALOMAS - VILLA EL SALVADOR LIM', 'HLC' => 'LIM-27' , 'email_jw' => '3CEmerson@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 11, 'ceh2_id' => 11]);
		Person::create(['nombre' => 'Luper', 'apaterno' => 'Chávez', 'amaterno' => 'Luna', 'full_name' => 'Chávez Luna Luper', 'tipo' => 'GVP', 'phone' => '936052042', 'congregacion' => '(1693) PARAISO - VILLA EL SALVADOR LIM', 'HLC' => 'LIM-26' , 'email_jw' => 'LuperChavez@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 11, 'ceh2_id' => 11]);
		Person::create(['nombre' => 'Isaac Marino', 'apaterno' => 'Chiriboga', 'amaterno' => 'Zegarra', 'full_name' => 'Chiriboga Zegarra Isaac Marino', 'tipo' => 'GVP', 'phone' => '933680558', 'congregacion' => '(14495) JORGE CHAVEZ - COMAS LIM', 'HLC' => 'LIM-06' , 'email_jw' => 'isaac2011@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 16, 'ceh2_id' => 16]);
		Person::create(['nombre' => 'Juan Moises', 'apaterno' => 'Choque', 'amaterno' => 'Quispe', 'full_name' => 'Choque Quispe Juan Moises', 'tipo' => 'GVP', 'phone' => '997808688 ; 012879569 ; 994701058', 'congregacion' => '(927) SUR - VILLA EL SALVADOR LIM', 'HLC' => 'LIM-27' , 'email_jw' => 'JuanChoque1@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 11, 'ceh2_id' => 11]);
		Person::create(['nombre' => 'Omar Jesús', 'apaterno' => 'Cornelio', 'amaterno' => 'Rajo', 'full_name' => 'Cornelio Rajo Omar Jesús', 'tipo' => 'GVP', 'phone' => '941709017; 014581323', 'congregacion' => '(8854) SHARON - SAN JUAN DE LURIGANCHO LIM', 'HLC' => 'LIM-13' , 'email_jw' => 'OCornelio@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 15, 'ceh2_id' => 18]);
		Person::create(['nombre' => 'Víctor Joselo', 'apaterno' => 'Cortéz', 'amaterno' => 'Pérez', 'full_name' => 'Cortéz Pérez Víctor Joselo', 'tipo' => 'GVP', 'phone' => '935228455', 'congregacion' => '(15303) CALIFORNIA - SAN MARTIN DE PORRES LIM', 'HLC' => 'LIM-08' , 'email_jw' => 'VictorCortezPere64@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 27, 'ceh2_id' => 21]);
		Person::create(['nombre' => 'Andrés Josué', 'apaterno' => 'Cruces', 'amaterno' => 'Mejia', 'full_name' => 'Cruces Mejia Andrés Josué', 'tipo' => 'GVP', 'phone' => '944449507', 'congregacion' => '(8896) PANDO - LIMA LIM', 'HLC' => 'LIM-11' , 'email_jw' => 'AndresCruces1@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 7, 'ceh2_id' => 2]);
		Person::create(['nombre' => 'Dennis', 'apaterno' => 'Cueva', 'amaterno' => 'Moscoso', 'full_name' => 'Cueva Moscoso Dennis', 'tipo' => 'GVP', 'phone' => '993839633', 'congregacion' => '(8037) CASUARINAS COLLIQUE - COMAS LIM', 'HLC' => 'LIM-04' , 'email_jw' => 'DennisC9@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 16, 'ceh2_id' => 16]);
		Person::create(['nombre' => 'Giancarlo', 'apaterno' => 'Espinaque', 'amaterno' => 'Mora', 'full_name' => 'Espinaque Mora Giancarlo', 'tipo' => 'GVP', 'phone' => '930105013', 'congregacion' => '(14854) OASIS DE VILLA QUECHUA - VILLA EL SALVADOR LIM', 'HLC' => 'LIM-Q02' , 'email_jw' => 'GiancarloE2@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 11, 'ceh2_id' => 11]);
		Person::create(['nombre' => 'Alonso Vidal', 'apaterno' => 'Espinoza', 'amaterno' => 'Sánchez', 'full_name' => 'Espinoza Sánchez Alonso Vidal', 'tipo' => 'GVP', 'phone' => '922166137', 'congregacion' => '(174) BELLAVISTA - LIM', 'HLC' => 'LIM-09' , 'email_jw' => 'alonespinoza@hotmail.com ; 1alonsoe@jwpub.org', 'email' => '', 'is_new' => 'A', 'ceh_id' => 13, 'ceh2_id' => 28]);
		Person::create(['nombre' => 'Marko Jordan ', 'apaterno' => 'Espiritu', 'amaterno' => 'Martinez', 'full_name' => 'Espiritu Martinez Marko Jordan ', 'tipo' => 'GVP', 'phone' => '980080405', 'congregacion' => '(1859) PALOMAS - VILLA EL SALVADOR LIM', 'HLC' => 'LIM-27' , 'email_jw' => '9EMarko@jwpub.org', 'email' => '', 'is_new' => 'A', 'ceh_id' => 17, 'ceh2_id' => 11]);
		Person::create(['nombre' => 'Luis Filomeno', 'apaterno' => 'Espiritu', 'amaterno' => 'Torero', 'full_name' => 'Espiritu Torero Luis Filomeno', 'tipo' => 'GVP', 'phone' => '980080360', 'congregacion' => '(1859) PALOMAS - VILLA EL SALVADOR LIM', 'HLC' => 'LIM-27' , 'email_jw' => 'LuisE11@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 17, 'ceh2_id' => 11]);
		Person::create(['nombre' => 'Oscar Joel', 'apaterno' => 'Farfán', 'amaterno' => 'Suárez', 'full_name' => 'Farfán Suárez Oscar Joel', 'tipo' => 'GVP', 'phone' => '994513958', 'congregacion' => '(927) SUR - VILLA EL SALVADOR LIM', 'HLC' => 'LIM-27' , 'email_jw' => 'OscarF14@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 11, 'ceh2_id' => 11]);
		Person::create(['nombre' => 'Pedro Javier', 'apaterno' => 'Fiestas', 'amaterno' => 'Eche', 'full_name' => 'Fiestas Eche Pedro Javier', 'tipo' => 'GVP', 'phone' => '994273779', 'congregacion' => '(8847) STELLA MARIS - BELLAVISTA LIM', 'HLC' => 'LIM-09' , 'email_jw' => '42FPedro@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 28, 'ceh2_id' => 28]);
		Person::create(['nombre' => 'Luis Reynaldo', 'apaterno' => 'Flores', 'amaterno' => 'Erique', 'full_name' => 'Flores Erique Luis Reynaldo', 'tipo' => 'GVP', 'phone' => '965923350', 'congregacion' => '(8706) VILLA HERMOSA - EL AGUSTINO LIM', 'HLC' => 'LIM-18' , 'email_jw' => 'luisflorese_tj@hotmail.com ; luisflores7@jwpub.org', 'email' => '', 'is_new' => 'A', 'ceh_id' => 18, 'ceh2_id' => 0]);
		Person::create(['nombre' => 'Edilberto', 'apaterno' => 'Garces', 'amaterno' => 'Miñan', 'full_name' => 'Garces Miñan Edilberto', 'tipo' => 'GVP', 'phone' => '945743257; 013660682', 'congregacion' => '(1578) LOS PILARES - CALLAO LIM', 'HLC' => 'LIM-09' , 'email_jw' => 'GarcesMinaE4@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 13, 'ceh2_id' => 28]);
		Person::create(['nombre' => 'Abel Humberto', 'apaterno' => 'Gaspar', 'amaterno' => 'Moreno', 'full_name' => 'Gaspar Moreno Abel Humberto', 'tipo' => 'GVP', 'phone' => '990728221', 'congregacion' => '(7476) BENJAMIN - CHILCA LIM', 'HLC' => 'LIM-S01' , 'email_jw' => 'GasparMoreA@jwpub.org ; agmpepe@hotmail.com', 'email' => '', 'is_new' => 'A', 'ceh_id' => 11, 'ceh2_id' => 9]);
		Person::create(['nombre' => 'José Antonio', 'apaterno' => 'Gilbonio', 'amaterno' => 'Tello', 'full_name' => 'Gilbonio Tello José Antonio', 'tipo' => 'GVP', 'phone' => '979264279', 'congregacion' => '(15013) SUR QUECHUA - VILLA EL SALVADOR LIM', 'HLC' => 'LIM-Q02' , 'email_jw' => 'GILBONIOJOSE@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 24, 'ceh2_id' => 11]);
		Person::create(['nombre' => 'Yuri', 'apaterno' => 'Heredia', 'amaterno' => 'Velorio', 'full_name' => 'Heredia Velorio Yuri', 'tipo' => 'GVP', 'phone' => '996659311', 'congregacion' => '(14266) LOS PRÓCERES - SANTIAGO DE SURCO LIM', 'HLC' => 'LIM-25' , 'email_jw' => 'YuriH12@jwpub.org ; Yheredia2005@yahoo.com', 'email' => '', 'is_new' => 'A', 'ceh_id' => 1, 'ceh2_id' => 1]);
		Person::create(['nombre' => 'Eduardo', 'apaterno' => 'Hernandez', 'amaterno' => 'Urrutia', 'full_name' => 'Hernandez Urrutia Eduardo', 'tipo' => 'GVP', 'phone' => '963743454; 014186703', 'congregacion' => '(15246) LA ALBORADA - LIMA LIM', 'HLC' => 'LIM-11' , 'email_jw' => 'EduardoHernandez48@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 2, 'ceh2_id' => 13]);
		Person::create(['nombre' => 'Noel', 'apaterno' => 'Huillca', 'amaterno' => 'Huamaní', 'full_name' => 'Huillca Huamaní Noel', 'tipo' => 'GVP', 'phone' => '945641484', 'congregacion' => '(356) FLORES CHACARILLA - SAN JUAN DE LURIGANCHO LIM', 'HLC' => 'LIM-16' , 'email_jw' => 'nhuillca@jwpub.org ; noel.logan@gmail.com', 'email' => '', 'is_new' => 'A', 'ceh_id' => 8, 'ceh2_id' => 15]);
		Person::create(['nombre' => 'Antonio', 'apaterno' => 'Ignacio', 'amaterno' => 'Pisfil', 'full_name' => 'Ignacio Pisfil Antonio', 'tipo' => 'GVP', 'phone' => '989791496', 'congregacion' => '(14869) LURIN QUECHUA - LURIN LIM', 'HLC' => 'LIM-Q02' , 'email_jw' => 'IgnacioA6@jwpub.org', 'email' => '', 'is_new' => 'A', 'ceh_id' => 16, 'ceh2_id' => 16]);
		Person::create(['nombre' => 'Marco Antonio', 'apaterno' => 'La Rosa', 'amaterno' => 'Montoya', 'full_name' => 'La Rosa Montoya Marco Antonio', 'tipo' => 'GVP', 'phone' => '980826918 ; 012886626', 'congregacion' => '(570) EMANCIPACION - LIMA LIM', 'HLC' => 'LIM-11' , 'email_jw' => 'MLaRosa2@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 20, 'ceh2_id' => 7]);
		Person::create(['nombre' => 'Armando Humberto', 'apaterno' => 'Letona', 'amaterno' => 'Tasaico', 'full_name' => 'Letona Tasaico Armando Humberto', 'tipo' => 'GVP', 'phone' => '993013108; 014108585', 'congregacion' => '(15172) MARIATEGUI - VILLA EL SALVADOR LIM', 'HLC' => 'LIM-27' , 'email_jw' => 'ArmandoL19@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 11, 'ceh2_id' => 11]);
		Person::create(['nombre' => 'Jonathan Gorki Pablo', 'apaterno' => 'Llontop', 'amaterno' => 'Chang', 'full_name' => 'Llontop Chang Jonathan Gorki Pablo', 'tipo' => 'GVP', 'phone' => '983430675; 012804127', 'congregacion' => '(15248) VILLA DEL MAR - VILLA EL SALVADOR LIM', 'HLC' => 'LIM-27' , 'email_jw' => 'JonathanL50@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 24, 'ceh2_id' => 11]);
		Person::create(['nombre' => 'Luigi Bernardo', 'apaterno' => 'Mandujano', 'amaterno' => 'Reyes', 'full_name' => 'Mandujano Reyes Luigi Bernardo', 'tipo' => 'GVP', 'phone' => '940561718 ; 013617230', 'congregacion' => '(15256) 24 DE JUNIO - VILLA EL SALVADOR LIM', 'HLC' => 'LIM-27' , 'email_jw' => 'MandujanoRL4@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 10, 'ceh2_id' => 11]);
		Person::create(['nombre' => 'Mario', 'apaterno' => 'Marticorena', 'amaterno' => 'Valderrama', 'full_name' => 'Marticorena Valderrama Mario', 'tipo' => 'GVP', 'phone' => '999496161', 'congregacion' => '(15019) LARCO DE MIRAFLORES - MIRAFLORES LIM', 'HLC' => 'LIM-20' , 'email_jw' => 'mariojesus_marticorena@hotmail.com ; marticorenmario@jwpub.org ', 'email' => '', 'is_new' => 'A', 'ceh_id' => 4, 'ceh2_id' => 5]);
		Person::create(['nombre' => 'Angel Miguel', 'apaterno' => 'Martinez', 'amaterno' => 'Girón', 'full_name' => 'Martinez Girón Angel Miguel', 'tipo' => 'GVP', 'phone' => '993119695 ; 012833945', 'congregacion' => '(15883) CACERES - SAN JUAN DE MIRAFLORES LIM', 'HLC' => 'LIM-21' , 'email_jw' => 'MARTINEZANGEL14@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 24, 'ceh2_id' => 24]);
		Person::create(['nombre' => 'Josue', 'apaterno' => 'Maza', 'amaterno' => 'Valerio', 'full_name' => 'Maza Valerio Josue', 'tipo' => 'GVP', 'phone' => '977809392 / 013871728', 'congregacion' => '(14470) EL TREBOL - SAN JUAN DE LURIGANCHO LIM', 'HLC' => 'LIM-13' , 'email_jw' => 'JMVb23a2K@jwpub.org ; jmv_1974@hotmail.com', 'email' => '', 'is_new' => 'A', 'ceh_id' => 8, 'ceh2_id' => 15]);
		Person::create(['nombre' => 'Víctor David', 'apaterno' => 'Medina', 'amaterno' => 'Tito', 'full_name' => 'Medina Tito Víctor David', 'tipo' => 'GVP', 'phone' => '989698987', 'congregacion' => '(15060) LA ESTANCIA - LURIN LIM', 'HLC' => 'LIM-28' , 'email_jw' => 'victormedinatito29@jwpub.org ; V.D.medina@hotmail.com', 'email' => '', 'is_new' => 'A', 'ceh_id' => 11, 'ceh2_id' => 9]);
		Person::create(['nombre' => 'Paúl César', 'apaterno' => 'Mena', 'amaterno' => 'Aniceto', 'full_name' => 'Mena Aniceto Paúl César', 'tipo' => 'GVP', 'phone' => '987012148', 'congregacion' => '(810) CARMEN DE LA LEGUA - CARMEN DE LA LEGUA REYNOSO LIM', 'HLC' => 'LIM-11' , 'email_jw' => '1MPaul@jwpub.org', 'email' => '', 'is_new' => 'A', 'ceh_id' => 13, 'ceh2_id' => 28]);
		Person::create(['nombre' => 'Ricardo Arturo', 'apaterno' => 'Morales', 'amaterno' => 'Gómez', 'full_name' => 'Morales Gómez Ricardo Arturo', 'tipo' => 'GVP', 'phone' => '990089809', 'congregacion' => '(15222) TRIUNFO NUEVO - VILLA MARIA DEL TRIUNFO LIM', 'HLC' => 'LIM-23' , 'email_jw' => 'RicardoM16@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 10, 'ceh2_id' => 24]);
		Person::create(['nombre' => 'Edison Fernando', 'apaterno' => 'Morán', 'amaterno' => 'Contreras', 'full_name' => 'Morán Contreras Edison Fernando', 'tipo' => 'GVP', 'phone' => '970010171', 'congregacion' => '(15495) GOSEN - VILLA EL SALVADOR LIM', 'HLC' => 'LIM-28' , 'email_jw' => 'MoranContrEdison@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 10, 'ceh2_id' => 11]);
		Person::create(['nombre' => 'Miqueas', 'apaterno' => 'Moreno', 'amaterno' => 'Talaverano', 'full_name' => 'Moreno Talaverano Miqueas', 'tipo' => 'GVP', 'phone' => '949944949 ; 997244338', 'congregacion' => '(16212) MI PERU BAJO - VENTANILLA LIM', 'HLC' => 'LIM-03' , 'email_jw' => 'MiqueasM@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 16, 'ceh2_id' => 16]);
		Person::create(['nombre' => 'Rodolfo Dante', 'apaterno' => 'Moscoso', 'amaterno' => 'Casapaico', 'full_name' => 'Moscoso Casapaico Rodolfo Dante', 'tipo' => 'GVP', 'phone' => '964173212 ; 016216710', 'congregacion' => '(15102) PEDREGAL - HUAROCHIRI LIM', 'HLC' => 'LIM-14' , 'email_jw' => 'RMoscosoCas@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 12, 'ceh2_id' => 8]);
		Person::create(['nombre' => 'Luis Alberto', 'apaterno' => 'Muñoz', 'amaterno' => 'Castillo', 'full_name' => 'Muñoz Castillo Luis Alberto', 'tipo' => 'GVP', 'phone' => '984713706; 014363183', 'congregacion' => '(1958) ROSA TORO - SAN LUIS LIM', 'HLC' => 'LIM-19' , 'email_jw' => 'LuisMunoz10@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 26, 'ceh2_id' => 26]);
		Person::create(['nombre' => 'Omar', 'apaterno' => 'Nieva', 'amaterno' => 'Valeriano', 'full_name' => 'Nieva Valeriano Omar', 'tipo' => 'GVP', 'phone' => '931718288', 'congregacion' => '(15248) VILLA DEL MAR - VILLA EL SALVADOR LIM', 'HLC' => 'LIM-27' , 'email_jw' => 'OmarN15@jwpub.org', 'email' => '', 'is_new' => 'A', 'ceh_id' => 11, 'ceh2_id' => 11]);
		Person::create(['nombre' => 'Javier Armando', 'apaterno' => 'Obregón', 'amaterno' => 'Mallqui', 'full_name' => 'Obregón Mallqui Javier Armando', 'tipo' => 'GVP', 'phone' => '939892305', 'congregacion' => '(1271) PUENTE PIEDRA CENTRAL - PUENTE PIEDRA LIM', 'HLC' => 'LIM-01' , 'email_jw' => '1JavierObregon@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 16, 'ceh2_id' => 16]);
		Person::create(['nombre' => 'Hector Ricardo', 'apaterno' => 'Ortecho', 'amaterno' => 'Rodas', 'full_name' => 'Ortecho Rodas Hector Ricardo', 'tipo' => 'GVP', 'phone' => '950061954; 013365003', 'congregacion' => '(8250) NACIONES - LIMA LIM', 'HLC' => 'LIM-11' , 'email_jw' => 'HectorO11@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 13, 'ceh2_id' => 28]);
		Person::create(['nombre' => 'Nelver Alcides', 'apaterno' => 'Paz', 'amaterno' => 'Castro', 'full_name' => 'Paz Castro Nelver Alcides', 'tipo' => 'GVP', 'phone' => '988785180', 'congregacion' => '(15149) EL BOSQUE - RIMAC LIM', 'HLC' => 'LIM-12' , 'email_jw' => 'nelverpaz61@jwpub.org', 'email' => '', 'is_new' => 'A', 'ceh_id' => 6, 'ceh2_id' => 3]);
		Person::create(['nombre' => 'Ronald Guillermo', 'apaterno' => 'Pérez', 'amaterno' => 'Colan', 'full_name' => 'Pérez Colan Ronald Guillermo', 'tipo' => 'GVP', 'phone' => '941885522 ; 016470242', 'congregacion' => '(16279) CARLOS IZAGUIRRE - SAN MARTIN DE PORRES LIM', 'HLC' => 'LIM-07' , 'email_jw' => 'RonaldPerezColan10@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 27, 'ceh2_id' => 27]);
		Person::create(['nombre' => 'David Israel', 'apaterno' => 'Plasencia', 'amaterno' => 'Carrascal', 'full_name' => 'Plasencia Carrascal David Israel', 'tipo' => 'GVP', 'phone' => '975113421', 'congregacion' => '(331) CONDEVILLA - SAN MARTIN DE PORRES LIM', 'HLC' => 'LIM-12' , 'email_jw' => 'DavidP7@jwpub.org , plasenciadavid@hotmail.es', 'email' => '', 'is_new' => 'A', 'ceh_id' => 3, 'ceh2_id' => 3]);
		Person::create(['nombre' => 'Miguel Angel', 'apaterno' => 'Ramos', 'amaterno' => 'Rivas', 'full_name' => 'Ramos Rivas Miguel Angel', 'tipo' => 'GVP', 'phone' => '999919996; 015752835', 'congregacion' => '(349) ELMER FAUCETT - CALLAO LIM', 'HLC' => 'LIM-08' , 'email_jw' => 'RMiguel6@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 28, 'ceh2_id' => 21]);
		Person::create(['nombre' => 'Jorge Eduardo', 'apaterno' => 'Ramos', 'amaterno' => 'Saldaña', 'full_name' => 'Ramos Saldaña Jorge Eduardo', 'tipo' => 'GVP', 'phone' => '924370508', 'congregacion' => '(190) CHACARITA - CALLAO LIM', 'HLC' => 'LIM-09' , 'email_jw' => 'RJorge19@jwpub.org', 'email' => '', 'is_new' => 'A', 'ceh_id' => 28, 'ceh2_id' => 28]);
		Person::create(['nombre' => 'Neyler Abel', 'apaterno' => 'Reyes', 'amaterno' => 'Polo', 'full_name' => 'Reyes Polo Neyler Abel', 'tipo' => 'GVP', 'phone' => '976054407', 'congregacion' => '(1321) 27 DE MARZO - SAN JUAN DE LURIGANCHO LIM ', 'HLC' => 'LIM-14' , 'email_jw' => 'neylerreyes1@jwpub.org', 'email' => '', 'is_new' => 'A', 'ceh_id' => 12, 'ceh2_id' => 8]);
		Person::create(['nombre' => 'José Francisco', 'apaterno' => 'Reyes', 'amaterno' => 'Ramírez', 'full_name' => 'Reyes Ramírez José Francisco', 'tipo' => 'GVP', 'phone' => '988324929; 014334802', 'congregacion' => '(570) EMANCIPACION - LIMA LIM', 'HLC' => 'LIM-11' , 'email_jw' => 'ReyesJose55@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 6, 'ceh2_id' => 7]);
		Person::create(['nombre' => 'Luis Alberto', 'apaterno' => 'Ríos', 'amaterno' => 'Pérez', 'full_name' => 'Ríos Pérez Luis Alberto', 'tipo' => 'GVP', 'phone' => '995459022; 012847611', 'congregacion' => '(2956) IMPERIAL - LIM', 'HLC' => 'LIM-S01' , 'email_jw' => 'RiosPerezL@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 19, 'ceh2_id' => 19]);
		Person::create(['nombre' => 'Roddy Enzo', 'apaterno' => 'Robles', 'amaterno' => 'Guevara', 'full_name' => 'Robles Guevara Roddy Enzo', 'tipo' => 'GVP', 'phone' => '987769883', 'congregacion' => '(8847) STELLA MARIS - BELLAVISTA LIM', 'HLC' => 'LIM-09' , 'email_jw' => '12EnzoR@jwpub.org', 'email' => '', 'is_new' => 'A', 'ceh_id' => 28, 'ceh2_id' => 28]);
		Person::create(['nombre' => 'Johnny Martin', 'apaterno' => 'Rodríguez', 'amaterno' => 'Díaz', 'full_name' => 'Rodríguez Díaz Johnny Martin', 'tipo' => 'GVP', 'phone' => '993236510', 'congregacion' => '(14478) OQUENDO - CALLAO LIM', 'HLC' => 'LIM-03' , 'email_jw' => 'JRodriguezD46@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 28, 'ceh2_id' => 27]);
		Person::create(['nombre' => 'Josué Luis', 'apaterno' => 'Rodríguez', 'amaterno' => 'Huamán', 'full_name' => 'Rodríguez Huamán Josué Luis', 'tipo' => 'GVP', 'phone' => '980037832', 'congregacion' => '(15383) EMAUS AYMARA - VILLA MARIA DEL TRIUNFO LIM', 'HLC' => 'PUN-AYM01' , 'email_jw' => '1JosueLR@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 17, 'ceh2_id' => 24]);
		Person::create(['nombre' => 'Isaac Enrique', 'apaterno' => 'Rojas', 'amaterno' => 'Bojorquez', 'full_name' => 'Rojas Bojorquez Isaac Enrique', 'tipo' => 'GVP', 'phone' => '959452063 ; 013422928', 'congregacion' => '(16212) MI PERU BAJO - VENTANILLA LIM', 'HLC' => 'LIM-03' , 'email_jw' => 'MALVINAS@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 16, 'ceh2_id' => 16]);
		Person::create(['nombre' => 'Teófanes Máximo', 'apaterno' => 'Rojas', 'amaterno' => 'García', 'full_name' => 'Rojas García Teófanes Máximo', 'tipo' => 'GVP', 'phone' => '958930744 ; 958930744', 'congregacion' => '(8227) MI PERU - VENTANILLA LIM', 'HLC' => 'LIM-03' , 'email_jw' => '11TRojas@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 16, 'ceh2_id' => 16]);
		Person::create(['nombre' => 'Octavio', 'apaterno' => 'Rondán', 'amaterno' => 'Alonso', 'full_name' => 'Rondán Alonso Octavio', 'tipo' => 'GVP', 'phone' => '991323888', 'congregacion' => '(612) MARIATEGUI - JESUS MARIA LIM', 'HLC' => 'LIM-10' , 'email_jw' => 'roctavio1@jwpub.org', 'email' => '', 'is_new' => 'A', 'ceh_id' => 7, 'ceh2_id' => 2]);
		Person::create(['nombre' => 'Francisco Gonzalo', 'apaterno' => 'Samillán', 'amaterno' => 'Carrasco', 'full_name' => 'Samillán Carrasco Francisco Gonzalo', 'tipo' => 'GVP', 'phone' => '936552313; 016936903', 'congregacion' => '(14450) LOS JAZMINES - VILLA EL SALVADOR LIM', 'HLC' => 'LIM-24' , 'email_jw' => 'FRANCISCOSAMILLANCA2@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 10, 'ceh2_id' => 24]);
		Person::create(['nombre' => 'Jesus Manuel', 'apaterno' => 'Sanchez', 'amaterno' => 'Avila', 'full_name' => 'Sanchez Avila Jesus Manuel', 'tipo' => 'GVP', 'phone' => '995183266', 'congregacion' => '(14495) JORGE CHAVEZ - COMAS LIM', 'HLC' => 'LIM-06' , 'email_jw' => '16SJesus@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 16, 'ceh2_id' => 16]);
		Person::create(['nombre' => 'Rodolfo', 'apaterno' => 'Sánchez', 'amaterno' => 'Reátegui', 'full_name' => 'Sánchez Reátegui Rodolfo', 'tipo' => 'GVP', 'phone' => '936020990', 'congregacion' => '(919) LOS ANGELES - VILLA EL SALVADOR LIM', 'HLC' => 'LIM-26' , 'email_jw' => 'SRodolfo1@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 10, 'ceh2_id' => 11]);
		Person::create(['nombre' => 'Angel Walter', 'apaterno' => 'Sanchez', 'amaterno' => 'Yupanqui', 'full_name' => 'Sanchez Yupanqui Angel Walter', 'tipo' => 'GVP', 'phone' => '963523023', 'congregacion' => '(15065) PAYET LAS MALVINAS - INDEPENDENCIA LIM', 'HLC' => 'LIM-06' , 'email_jw' => 'ASanchezYup@jwpub.org , angelwaltersanchez34@gmail.com', 'email' => '', 'is_new' => 'A', 'ceh_id' => 21, 'ceh2_id' => 27]);
		Person::create(['nombre' => 'Ronald Enrique', 'apaterno' => 'Sánchez', 'amaterno' => '', 'full_name' => 'Sánchez  Ronald Enrique', 'tipo' => 'GVP', 'phone' => '917608706', 'congregacion' => '(1214) ZARATE - SAN JUAN DE LURIGANCHO LIM', 'HLC' => 'LIM-16' , 'email_jw' => 'RonaldSanchez10@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 18, 'ceh2_id' => 15]);
		Person::create(['nombre' => 'Luis Gianfranco', 'apaterno' => 'Serquén', 'amaterno' => 'Saravia', 'full_name' => 'Serquén Saravia Luis Gianfranco', 'tipo' => 'GVP', 'phone' => '954441616 ; 015363977', 'congregacion' => '(14797) CARABAYLLO SEÑAS - CARABAYLLO LIM', 'HLC' => 'SLP-01' , 'email_jw' => 'GianfrancoS2@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 16, 'ceh2_id' => 16]);
		Person::create(['nombre' => 'Gunnar Armando', 'apaterno' => 'Serrano', 'amaterno' => 'Carbajal', 'full_name' => 'Serrano Carbajal Gunnar Armando', 'tipo' => 'GVP', 'phone' => '977782092 ; 017511729', 'congregacion' => '(14490) FLORES VIOLETAS - SAN JUAN DE LURIGANCHO LIM', 'HLC' => 'LIM-16' , 'email_jw' => '35GunnarS@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 26, 'ceh2_id' => 15]);
		Person::create(['nombre' => 'Gustavo Enrique', 'apaterno' => 'Sierra', 'amaterno' => 'Avalos', 'full_name' => 'Sierra Avalos Gustavo Enrique', 'tipo' => 'GVP', 'phone' => '962507302', 'congregacion' => '(8896) PANDO - LIMA LIM', 'HLC' => 'LIM-11' , 'email_jw' => 'SierraGustavo@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 2, 'ceh2_id' => 7]);
		Person::create(['nombre' => 'Rolando', 'apaterno' => 'Silva', 'amaterno' => 'Castro', 'full_name' => 'Silva Castro Rolando', 'tipo' => 'GVP', 'phone' => '991091703 ; 013883478', 'congregacion' => '(1768) CANTO REY - SAN JUAN DE LURIGANCHO LIM', 'HLC' => 'LIM-13' , 'email_jw' => 'RolandoS10@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 12, 'ceh2_id' => 12]);
		Person::create(['nombre' => 'Abrahán', 'apaterno' => 'Soto', 'amaterno' => '', 'full_name' => 'Soto  Abrahán', 'tipo' => 'GVP', 'phone' => '990483375', 'congregacion' => '(15727) MANCHAY - PACHACAMAC LIM', 'HLC' => 'LIM-22' , 'email_jw' => 'ASotoLlanos@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 22, 'ceh2_id' => 22]);
		Person::create(['nombre' => 'Juan Jose', 'apaterno' => 'Tacuchi', 'amaterno' => 'Reyes', 'full_name' => 'Tacuchi Reyes Juan Jose', 'tipo' => 'GVP', 'phone' => '957561581 ; 016963038', 'congregacion' => '(15198) GERMAN AGUIRRE - SAN MARTIN DE PORRES LIM', 'HLC' => 'LIM-12' , 'email_jw' => 'TacuchireyJuan1@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 21, 'ceh2_id' => 21]);
		Person::create(['nombre' => 'Julio César', 'apaterno' => 'Tafur', 'amaterno' => 'Gálvez', 'full_name' => 'Tafur Gálvez Julio César', 'tipo' => 'GVP', 'phone' => '996435015 ; 013273320', 'congregacion' => '(34) MANZANILLA - LIMA LIM', 'HLC' => 'LIM-17' , 'email_jw' => 'JulioT26@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 23, 'ceh2_id' => 20]);
		Person::create(['nombre' => 'Víctor Enrique ', 'apaterno' => 'Trujillo', 'amaterno' => 'Rosado', 'full_name' => 'Trujillo Rosado Víctor Enrique ', 'tipo' => 'GVP', 'phone' => '980925789', 'congregacion' => '(15024) FLOR DE AMANCAES - RIMAC LIM', 'HLC' => 'LIM-12' , 'email_jw' => 'VictorT11@jwpub.org , victor_enrique98@hotmail.com', 'email' => '', 'is_new' => 'A', 'ceh_id' => 20, 'ceh2_id' => 3]);
		Person::create(['nombre' => 'Juan Carlos', 'apaterno' => 'Tulich', 'amaterno' => 'Barbarán', 'full_name' => 'Tulich Barbarán Juan Carlos', 'tipo' => 'GVP', 'phone' => '978997172', 'congregacion' => '(14472) SAN JUAN DE LURIGANCHO SEÑAS - SAN JUAN DE LURIGANCHO LIM', 'HLC' => 'SLP-01' , 'email_jw' => '20JTulich@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 18, 'ceh2_id' => 18]);
		Person::create(['nombre' => 'Francisco José', 'apaterno' => 'Valderrama', 'amaterno' => 'Zavaleta', 'full_name' => 'Valderrama Zavaleta Francisco José', 'tipo' => 'GVP', 'phone' => '931296243', 'congregacion' => '(1982) ALTA - VENTANILLA LIM', 'HLC' => 'LIM-03' , 'email_jw' => 'FVALDERRAMA1@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 16, 'ceh2_id' => 16]);
		Person::create(['nombre' => 'Luis Samuel', 'apaterno' => 'Valdiviezo', 'amaterno' => 'Uribe', 'full_name' => 'Valdiviezo Uribe Luis Samuel', 'tipo' => 'GVP', 'phone' => '989424638 ; 017469364', 'congregacion' => '(15262) EL MAESTRO - COMAS LIM', 'HLC' => 'LIM-06' , 'email_jw' => 'AYacarini4@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 16, 'ceh2_id' => 16]);
		Person::create(['nombre' => 'Oscar Miguel', 'apaterno' => 'Valeriano', 'amaterno' => 'Pacheco', 'full_name' => 'Valeriano Pacheco Oscar Miguel', 'tipo' => 'GVP', 'phone' => '991729567 / 012874634', 'congregacion' => '(15225) 6 DE AGOSTO - VILLA EL SALVADOR LIM', 'HLC' => 'LIM-27' , 'email_jw' => 'masterprint_on@hotmail.com', 'email' => '', 'is_new' => 'A', 'ceh_id' => 17, 'ceh2_id' => 11]);
		Person::create(['nombre' => 'Joel David', 'apaterno' => 'Vásquez', 'amaterno' => 'Cuellar', 'full_name' => 'Vásquez Cuellar Joel David', 'tipo' => 'GVP', 'phone' => '993335947 ; 016231554', 'congregacion' => '(15081) LAS AMÉRICAS - LIMA LIM', 'HLC' => 'LIM-17' , 'email_jw' => '1JoelVasquez@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 2, 'ceh2_id' => 14]);
		Person::create(['nombre' => 'Hermenegildo Moisés', 'apaterno' => 'Vega', 'amaterno' => 'Urbizagastegui', 'full_name' => 'Vega Urbizagastegui Hermenegildo Moisés', 'tipo' => 'GVP', 'phone' => '989969638', 'congregacion' => '(1875) HONOR Y LEALTAD - SANTIAGO DE SURCO LIM', 'HLC' => 'LIM-25' , 'email_jw' => 'HVegaUrbiza@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 14, 'ceh2_id' => 1]);
		Person::create(['nombre' => 'Miguel Angel', 'apaterno' => 'Vejarano', 'amaterno' => 'Mezarina', 'full_name' => 'Vejarano Mezarina Miguel Angel', 'tipo' => 'GVP', 'phone' => '999761224', 'congregacion' => '(638) NUEVO LURIN - LURIN LIM', 'HLC' => 'LIM-28' , 'email_jw' => 'MiguelV6@jwpub.org ; mezarina_art@outlook.com', 'email' => '', 'is_new' => 'A', 'ceh_id' => 11, 'ceh2_id' => 9]);
		Person::create(['nombre' => 'Luciano Máximo', 'apaterno' => 'Vivas', 'amaterno' => 'Astupuma', 'full_name' => 'Vivas Astupuma Luciano Máximo', 'tipo' => 'GVP', 'phone' => '981036120 ; 013276571', 'congregacion' => '(26) SANTOYO - EL AGUSTINO LIM', 'HLC' => 'LIM-17' , 'email_jw' => '4VLuciano@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 23, 'ceh2_id' => 20]);
		Person::create(['nombre' => 'Luis Fernando', 'apaterno' => 'Yactayo', 'amaterno' => 'Salirrosas', 'full_name' => 'Yactayo Salirrosas Luis Fernando', 'tipo' => 'GVP', 'phone' => '939186482', 'congregacion' => '(15396) TABLADA ANTIGUA - VILLA MARIA DEL TRIUNFO LIM', 'HLC' => 'LIM-27' , 'email_jw' => 'yactayo.luis@gmail.com ; yluis11@jwpub.org', 'email' => '', 'is_new' => 'A', 'ceh_id' => 10, 'ceh2_id' => 11]);
		Person::create(['nombre' => 'Miguel Angel', 'apaterno' => 'Yataco', 'amaterno' => 'Grimaldo', 'full_name' => 'Yataco Grimaldo Miguel Angel', 'tipo' => 'GVP', 'phone' => '944143565', 'congregacion' => '(15354) SEVILLA - VILLA EL SALVADOR LIM', 'HLC' => 'LIM-26' , 'email_jw' => 'YatacoM7@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 24, 'ceh2_id' => 11]);
		Person::create(['nombre' => 'José Manuel', 'apaterno' => 'Yarlequé', 'amaterno' => 'Rodriguez', 'full_name' => 'Yarlequé Rodriguez José Manuel', 'tipo' => 'GVP', 'phone' => '998329944', 'congregacion' => '(8284) SAN GERMAN - SAN MARTIN DE PORRES LIM', 'HLC' => 'LIM-08' , 'email_jw' => 'JManuelYarleque1@jwpub.org', 'email' => '', 'is_new' => 'A', 'ceh_id' => 3, 'ceh2_id' => 3]);
		Person::create(['nombre' => 'Andres Avelino', 'apaterno' => 'Yllanes', 'amaterno' => 'Coyllo', 'full_name' => 'Yllanes Coyllo Andres Avelino', 'tipo' => 'GVP', 'phone' => '999859717', 'congregacion' => '(8060) VISTA ALEGRE DE VILLA - CHORRILLOS LIM', 'HLC' => 'LIM-25' , 'email_jw' => 'AndresYllanes10@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 17, 'ceh2_id' => 17]);
		Person::create(['nombre' => 'Carlos Enrique', 'apaterno' => 'Zavala', 'amaterno' => 'Guerrero', 'full_name' => 'Zavala Guerrero Carlos Enrique', 'tipo' => 'GVP', 'phone' => '996668648', 'congregacion' => '(1578) LOS PILARES - CALLAO LIM', 'HLC' => 'LIM-09' , 'email_jw' => 'carloszavala230769@hotmail.com; zcarlos10@jwpub.org', 'email' => '', 'is_new' => 'A', 'ceh_id' => 28, 'ceh2_id' => 28]);
		Person::create(['nombre' => 'Eric Josué', 'apaterno' => 'Zavala', 'amaterno' => 'Torres', 'full_name' => 'Zavala Torres Eric Josué', 'tipo' => 'GVP', 'phone' => '987539287', 'congregacion' => '(15511) TABLADA VALLEJO - VILLA MARIA DEL TRIUNFO LIM', 'HLC' => 'LIM-27' , 'email_jw' => 'EricZ1@jwpub.org', 'email' => '', 'is_new' => 'N', 'ceh_id' => 24, 'ceh2_id' => 1]);


		$r = Hospital::create(['nombre' => 'Clínica Anglo Americana', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - ANGLO AMERICANA', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([5, 80]);
		$r = Hospital::create(['nombre' => 'Clínica Avendaño', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - AVENDAÑO', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([1, 36]);
		$r = Hospital::create(['nombre' => 'Clínica Bellavista AUNA', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - BELLAVISTA AUNA', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([28, 67, 69, 101, 132]);
		$r = Hospital::create(['nombre' => 'Clínica Campos', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - CAMPOS CAÑETE', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([19, 100]);
		$r = Hospital::create(['nombre' => 'Clínica Médica Cayetano Heredia', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - CAYETANO HEREDIA', 'clase' => '0', 'prioridad' => 'B']);
		$r->peaple()->sync([3, 41, 93, 95, 119]);
		$r = Hospital::create(['nombre' => 'Clínica de Especialidades Medicas', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - CLINICA DE ESPECIALIDADES MEDICAS', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([4, 32]);
		$r = Hospital::create(['nombre' => 'Clínica Delgado', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - DELGADO', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([1, 36]);
		$r = Hospital::create(['nombre' => 'Clínica Good Hope', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - GOOD HOPE', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([1, 36]);
		$r = Hospital::create(['nombre' => 'Clínica Guadalupe', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - GUADALUPE', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([17, 131]);
		$r = Hospital::create(['nombre' => 'Clínica del INCA', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - INCA', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([1, 36]);
		$r = Hospital::create(['nombre' => 'Instituto Oncológico Miraflores', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - INSTITUTO ONCOLOGICO MIRAFLORES', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([5, 80]);
		$r = Hospital::create(['nombre' => 'Clínica Internacional (Lima)', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - INTERNACIONAL, SEDE LIMA', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([6, 51]);
		$r = Hospital::create(['nombre' => 'Clínica Internacional (San Borja)', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - INTERNACIONAL, SEDE SAN BORJA', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([14, 124]);
		$r = Hospital::create(['nombre' => 'Clínica Javier Prado', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - JAVIER PRADO', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([2, 106]);
		$r = Hospital::create(['nombre' => 'Clínica Jesús del Norte', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - JESUS DEL NORTE', 'clase' => '0', 'prioridad' => 'B']);
		$r->peaple()->sync([27, 30, 94, 102, 110]);
		$r = Hospital::create(['nombre' => 'Clínica La Luz', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - LA LUZ', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([7, 99]);
		$r = Hospital::create(['nombre' => 'Clínica Las Américas', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - LAS AMERICAS', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([2, 106]);
		$r = Hospital::create(['nombre' => 'Clínica las Palmeras', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - LAS PALMERAS', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([2, 106]);
		$r = Hospital::create(['nombre' => 'Clínica Limatambo (San Isidro)', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - LIMATAMBO, SEDE SAN ISIDRO', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([1, 36]);
		$r = Hospital::create(['nombre' => 'Clínica los Andes', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - LOS ANDES', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([5, 80]);
		$r = Hospital::create(['nombre' => 'Clínica Maison de Santé', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - MAISON DE SANTE', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([6, 51]);
		$r = Hospital::create(['nombre' => 'Clínica Miraflores', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - MIRAFLORES', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([4, 32]);
		$r = Hospital::create(['nombre' => 'Clínica Montesur', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - MONTE SUR', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([26, 89]);
		$r = Hospital::create(['nombre' => 'Clínica Novocardio', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - NOVOCARDIO', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([2, 60]);
		$r = Hospital::create(['nombre' => 'Clínica Oncosalud (Miraflores)', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - ONCOSALUD, SEDE BENAVIDES', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([4, 32]);
		$r = Hospital::create(['nombre' => 'Clínica Oncosalud (San Borja)', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - ONCOSALUD, SEDE SAN BORJA', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([14, 124]);
		$r = Hospital::create(['nombre' => 'Clínica Padre Luis Tezza', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - PADRE LUIS TEZZA', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([26, 89]);
		$r = Hospital::create(['nombre' => 'Clínica Ricardo Palma', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - RICARDO PALMA', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([14, 124]);
		$r = Hospital::create(['nombre' => 'Clínica Rosalía Lavalle de Morales Macedo', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - ROSALIA LAVALLE DE MORALES MACEDO', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([5, 80]);
		$r = Hospital::create(['nombre' => 'Clínica San Bernardo', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - SAN BERNARDO', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([7, 99]);
		$r = Hospital::create(['nombre' => 'Clínica San Camilo', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - SAN CAMILO', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([20, 35, 118, 127]);
		$r = Hospital::create(['nombre' => 'Clínica San Francisco', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - SAN FRANCISCO', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([7, 99]);
		$r = Hospital::create(['nombre' => 'Clínica San Gabriel', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - SAN GABRIEL', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([13, 43]);
		$r = Hospital::create(['nombre' => 'Clínica San Juan Bautista', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - SAN JUAN BAUTISTA', 'clase' => '0', 'prioridad' => 'B']);
		$r->peaple()->sync([15, 31, 46, 74, 82, 111, 113]);
		$r = Hospital::create(['nombre' => 'Clínica San Juan de Dios', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - SAN JUAN DE DIOS', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([23, 37]);
		$r = Hospital::create(['nombre' => 'Clínica San Judas Tadeo', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - SAN JUDAS TADEO', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([13, 73]);
		$r = Hospital::create(['nombre' => 'Clínica San Marcos', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - SAN MARCOS', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([7, 76]);
		$r = Hospital::create(['nombre' => 'Clínica San Miguel Arcángel', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - SAN MIGUEL', 'clase' => '0', 'prioridad' => 'B']);
		$r->peaple()->sync([12, 115]);
		$r = Hospital::create(['nombre' => 'Clínica San Pablo (Surco)', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - SAN PABLO, SEDE SURCO', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([26, 89]);
		$r = Hospital::create(['nombre' => 'Clínica San Pablo (Asia)', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - SAN PABLO, SERIE ASIA', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([9, 70, 83, 126]);
		$r = Hospital::create(['nombre' => 'Clínica San Vicente', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - SAN VICENTE', 'clase' => '0', 'prioridad' => 'B']);
		$r->peaple()->sync([21, 45, 59, 96, 117, 130]);
		$r = Hospital::create(['nombre' => 'Clínica SANNA El Golf', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - SANNA EL GOLF', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([2, 106]);
		$r = Hospital::create(['nombre' => 'Clínica SANNA San Borja', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - SANNA SAN BORJA', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([14, 124]);
		$r = Hospital::create(['nombre' => 'Clínica Santa Isabel', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - SANTA ISABEL', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([26, 89]);
		$r = Hospital::create(['nombre' => 'Clínica Santa Lucía', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - SANTA LUCIA', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([14, 124]);
		$r = Hospital::create(['nombre' => 'Clínica Santa María del Sur', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - SANTA MARIA DEL SUR', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([24, 33, 39, 81, 85, 103, 107]);
		$r = Hospital::create(['nombre' => 'Clínica Santa Mónica', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - SANTA MONICA', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([2, 106]);
		$r = Hospital::create(['nombre' => 'Clínica Stella Maris', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - STELLA MARIS', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([7, 76]);
		$r = Hospital::create(['nombre' => 'Clínica Versalles', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - VERSALLES', 'clase' => '0', 'prioridad' => 'B']);
		$r->peaple()->sync([16, 42, 48, 56, 61, 75, 108, 112, 122]);
		$r = Hospital::create(['nombre' => 'Clínica Vesalio', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - VESALIO', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([4, 32]);
		$r = Hospital::create(['nombre' => 'Clínica Virgen del Rosario', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - VIRGEN EL ROSARIO', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([2, 60]);
		$r = Hospital::create(['nombre' => 'Clínica Virgen Milagrosa', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - VIRGEN MILAGROSA', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([4, 32]);
		$r = Hospital::create(['nombre' => 'Clínica Vista Alegre', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - VISTA ALEGRE', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([1, 34, 72, 125]);
		$r = Hospital::create(['nombre' => 'Clínica Limatambo (SJL)', 'tipo' => 'CLINICA', 'alias' => 'CLINICA- LIMATAMBO, SEDE SJL', 'clase' => '0', 'prioridad' => 'B']);
		$r->peaple()->sync([18, 58, 120]);
		$r = Hospital::create(['nombre' => 'Clínica Montefiori', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - MONTEFIORI', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([23, 37]);
		$r = Hospital::create(['nombre' => 'Clínica San Felipe', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - SAN FELIPE', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([7, 114]);
		$r = Hospital::create(['nombre' => 'Policlínico Alberto Leonardo Barton Thompson', 'tipo' => 'ESSALUD', 'alias' => 'ESSALUD - ALBERTO L. BARTON THOMPSON', 'clase' => 'II-2', 'prioridad' => 'A']);
		$r->peaple()->sync([13, 28, 43, 63, 67, 69, 84, 92, 96, 97, 101, 102, 132]);
		$r = Hospital::create(['nombre' => 'Centro Nacional De Salud Renal', 'tipo' => 'ESSALUD', 'alias' => 'ESSALUD - CENTRO NACIONAL DE SALUD RENAL', 'clase' => 'III-2', 'prioridad' => 'A']);
		$r->peaple()->sync([2, 7, 51, 60, 73, 106, 114, 124]);
		$r = Hospital::create(['nombre' => 'Hospital EsSalud Edgardo Rebagliati Martins', 'tipo' => 'ESSALUD', 'alias' => 'ESSALUD - EDGARDO REBAGLIATI MARTINS', 'clase' => 'III-2', 'prioridad' => 'A']);
		$r->peaple()->sync([2, 7, 51, 60, 73, 106, 114, 124]);
		$r = Hospital::create(['nombre' => 'Hospital Guillermo Almenara Irigoyen', 'tipo' => 'ESSALUD', 'alias' => 'ESSALUD - GUILLERMO ALMENARA IRIGOYEN', 'clase' => 'III-2', 'prioridad' => 'A']);
		$r->peaple()->sync([6, 20, 41, 76, 93, 99, 119]);
		$r = Hospital::create(['nombre' => 'Complejo Hospitalario Guillermo Kaelin De La Fuente', 'tipo' => 'ESSALUD', 'alias' => 'ESSALUD - GUILLERMO KAELIN DE LA FUENTE', 'clase' => 'II-2', 'prioridad' => 'A']);
		$r->peaple()->sync([10, 11, 17, 24, 44, 50, 57, 66, 71, 78, 79, 90, 103, 123, 128, 133]);
		$r = Hospital::create(['nombre' => 'Hospital Carlos Alcántara Butterfield', 'tipo' => 'ESSALUD', 'alias' => 'ESSALUD - HOSPITAL CARLOS ALCANTARA BUTTERFIELD', 'clase' => 'II-1', 'prioridad' => 'B']);
		$r->peaple()->sync([22, 116]);
		$r = Hospital::create(['nombre' => 'Hospital EsSalud Emergencias Grau', 'tipo' => 'ESSALUD', 'alias' => 'ESSALUD - HOSPITAL EMERGENCIAS GRAU', 'clase' => 'III-1', 'prioridad' => 'A']);
		$r->peaple()->sync([6, 20, 41, 76, 93, 99, 119]);
		$r = Hospital::create(['nombre' => 'Hospital Essalud I Octavio Mongrut Muñoz', 'tipo' => 'ESSALUD', 'alias' => 'ESSALUD - HOSPITAL I OCTAVIO MONGRUT MUÑOZ', 'clase' => 'II-1', 'prioridad' => 'B']);
		$r->peaple()->sync([28, 63, 97]);
		$r = Hospital::create(['nombre' => 'Hospital II Cañete', 'tipo' => 'ESSALUD', 'alias' => 'ESSALUD - HOSPITAL II CAÑETE', 'clase' => 'II-2', 'prioridad' => 'A']);
		$r->peaple()->sync([9, 19, 100]);
		$r = Hospital::create(['nombre' => 'Hospital II Lima Norte Callao “Luis Negreiros Vega”', 'tipo' => 'ESSALUD', 'alias' => 'ESSALUD - HOSPITAL II LUIS NEGREIROS', 'clase' => 'II-2', 'prioridad' => 'A']);
		$r->peaple()->sync([13, 28, 43, 63, 67, 69, 84, 92, 96, 97, 101, 102, 132]);
		$r = Hospital::create(['nombre' => 'Hospital II Ramón Castilla', 'tipo' => 'ESSALUD', 'alias' => 'ESSALUD - HOSPITAL II RAMON CASTILLA', 'clase' => 'II-2', 'prioridad' => 'A']);
		$r->peaple()->sync([3, 21, 27, 30, 45, 59, 94, 95, 110, 117, 130]);
		$r = Hospital::create(['nombre' => 'Hospital II Clínica Geriatrica San Isidro Labrador', 'tipo' => 'ESSALUD', 'alias' => 'ESSALUD - HOSPITAL II SAN ISIDRO LABRADOR', 'clase' => 'II-2', 'prioridad' => 'A']);
		$r->peaple()->sync([14, 22, 25, 37, 38, 52, 116]);
		$r = Hospital::create(['nombre' => 'Hospital II Vitarte', 'tipo' => 'ESSALUD', 'alias' => 'ESSALUD - HOSPITAL II VITARTE', 'clase' => 'II-2', 'prioridad' => 'A']);
		$r->peaple()->sync([14, 22, 25, 37, 38, 52, 116]);
		$r = Hospital::create(['nombre' => 'Hospital III Suárez Angamos', 'tipo' => 'ESSALUD', 'alias' => 'ESSALUD - HOSPITAL III ANGAMOS', 'clase' => 'III-1', 'prioridad' => 'A']);
		$r->peaple()->sync([1, 4, 5, 14, 32, 34, 36, 72, 80, 125]);
		$r = Hospital::create(['nombre' => 'Hospital Jorge Voto Bernales Corpancho', 'tipo' => 'ESSALUD', 'alias' => 'ESSALUD - HOSPITAL JORGE VOTO BERNALES CORPANCHO', 'clase' => 'II-1', 'prioridad' => 'B']);
		$r->peaple()->sync([22, 116]);
		$r = Hospital::create(['nombre' => 'Hospital Marino Molina Scippa', 'tipo' => 'ESSALUD', 'alias' => 'ESSALUD - HOSPITAL MARINO MOLINA SCIPPA', 'clase' => 'II-1', 'prioridad' => 'B']);
		$r->peaple()->sync([16, 42, 48, 56, 61, 75, 108, 112, 122]);
		$r = Hospital::create(['nombre' => 'Hospital EsSalud Uldarico Rocca Fernández', 'tipo' => 'ESSALUD', 'alias' => 'ESSALUD - HOSPITAL ULDARICO ROCCA FERNANDEZ', 'clase' => 'II-1', 'prioridad' => 'B']);
		$r->peaple()->sync([11, 29, 40, 44, 47, 50, 53, 54, 55, 57, 62, 64, 65, 66, 71, 77, 78, 79, 86, 90, 109, 123, 128, 129, 133]);
		$r = Hospital::create(['nombre' => 'Instituto Nacional Cardiovascular', 'tipo' => 'ESSALUD', 'alias' => 'ESSALUD - INCOR-CARDIOVASCULAR', 'clase' => 'III-2', 'prioridad' => 'A']);
		$r->peaple()->sync([2, 7, 51, 60, 73, 106, 114, 124]);
		$r = Hospital::create(['nombre' => 'Hospital Nacional Alberto Sabogal Sologuren', 'tipo' => 'ESSALUD', 'alias' => 'ESSALUD - SABOGAL SOLOGUREN', 'clase' => 'III-1', 'prioridad' => 'A']);
		$r->peaple()->sync([13, 28, 43, 63, 67, 69, 84, 92, 96, 97, 101, 102, 132]);
		$r = Hospital::create(['nombre' => 'Hospital Central FAP', 'tipo' => 'FAP', 'alias' => 'FAP - HOSPITAL CENTRAL FAP', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([5, 80]);
		$r = Hospital::create(['nombre' => 'Hospital Militar Central', 'tipo' => 'MILITAR', 'alias' => 'MILITAR - HOSPITAL MILITAR CENTRAL', 'clase' => 'III-1', 'prioridad' => 'B']);
		$r->peaple()->sync([7, 114]);
		$r = Hospital::create(['nombre' => 'Hospital Nacional Arzobispo Loayza', 'tipo' => 'MINSA', 'alias' => 'MINSA - ARZOBISPO LOAYZA', 'clase' => 'III-1', 'prioridad' => 'A']);
		$r->peaple()->sync([3, 21, 27, 30, 45, 59, 94, 95, 110, 117, 130]);
		$r = Hospital::create(['nombre' => 'Hospital Carlos Lanfranco La Hoz', 'tipo' => 'MINSA', 'alias' => 'MINSA - CARLOS LAFRANCO LA HOZ', 'clase' => 'II-2', 'prioridad' => 'A']);
		$r->peaple()->sync([6, 16, 42, 48, 49, 56, 61, 75, 87, 91, 104, 105, 108, 112, 121, 122]);
		$r = Hospital::create(['nombre' => 'Hospital Cayetano Heredia', 'tipo' => 'MINSA', 'alias' => 'MINSA - CAYETANO HEREDIA', 'clase' => 'III-1', 'prioridad' => 'A']);
		$r->peaple()->sync([3, 21, 27, 30, 45, 59, 94, 95, 110, 117, 130]);
		$r = Hospital::create(['nombre' => 'Hospital Nacional Daniel Alcides Carrión', 'tipo' => 'MINSA', 'alias' => 'MINSA - DANIEL ALCIDES CARRIÓN', 'clase' => 'III-1', 'prioridad' => 'A']);
		$r->peaple()->sync([13, 28, 43, 63, 67, 69, 84, 92, 96, 97, 101, 102, 132]);
		$r = Hospital::create(['nombre' => 'Hospital Nacional Docente Madre Niño San Bartolomé', 'tipo' => 'MINSA', 'alias' => 'MINSA - DOCENTE MADRE NIÑO "SAN BARTOLOMÉ"', 'clase' => 'III-1', 'prioridad' => 'A']);
		$r->peaple()->sync([3, 21, 27, 30, 45, 59, 94, 95, 110, 117, 130]);
		$r = Hospital::create(['nombre' => 'Hospital Nacional Dos de Mayo', 'tipo' => 'MINSA', 'alias' => 'MINSA - DOS DE MAYO', 'clase' => 'III-1', 'prioridad' => 'A']);
		$r->peaple()->sync([8, 23, 26, 74, 82, 89, 113, 118, 127]);
		$r = Hospital::create(['nombre' => 'Hospital de Emergencias Villa El Salvador', 'tipo' => 'MINSA', 'alias' => 'MINSA - EMERGENCIAS VILLA EL SALVADOR', 'clase' => 'III-1', 'prioridad' => 'A']);
		$r->peaple()->sync([10, 11, 17, 24, 29, 40, 47, 53, 54, 55, 62, 64, 65, 70, 77, 83, 86, 126, 129]);
		$r = Hospital::create(['nombre' => 'Hospital Nacional Hipólito Unanue', 'tipo' => 'MINSA', 'alias' => 'MINSA - HIPOLITO UNANUE', 'clase' => 'III-1', 'prioridad' => 'A']);
		$r->peaple()->sync([12, 15, 18, 31, 35, 46, 58, 68, 88, 98, 111, 115, 120]);
		$r = Hospital::create(['nombre' => 'Hospital Lima Este Vitarte', 'tipo' => 'MINSA', 'alias' => 'MINSA - HOSPITAL DE EMERGENCIAS LIMA ESTE - ATE VITARTE', 'clase' => 'II-2', 'prioridad' => 'A']);
		$r->peaple()->sync([14, 22, 25, 37, 38, 52, 116]);
		$r = Hospital::create(['nombre' => 'Hospital de Ventanilla', 'tipo' => 'MINSA', 'alias' => 'MINSA - HOSPITAL DE VENTANILLA', 'clase' => 'II-1', 'prioridad' => 'B']);
		$r->peaple()->sync([16, 49, 87, 91, 104, 105, 121]);
		$r = Hospital::create(['nombre' => 'Hospital de Emergencias Pediátricas', 'tipo' => 'MINSA', 'alias' => 'MINSA - HOSPITAL EMERGENCIAS PEDIATRICAS', 'clase' => 'III-1', 'prioridad' => 'A']);
		$r->peaple()->sync([6, 20, 41, 76, 93, 99, 119]);
		$r = Hospital::create(['nombre' => 'Hospital Hermilio Valdizan', 'tipo' => 'MINSA', 'alias' => 'MINSA - HOSPITAL HERMILIO VALDIZAN', 'clase' => 'III-1', 'prioridad' => 'A']);
		$r->peaple()->sync([14, 22, 25, 37, 38, 52, 116]);
		$r = Hospital::create(['nombre' => 'Hospital de Huaycán', 'tipo' => 'MINSA', 'alias' => 'MINSA - HOSPITAL HUAYCAN', 'clase' => 'II-2', 'prioridad' => 'A']);
		$r->peaple()->sync([14, 22, 25, 37, 38, 52, 116]);
		$r = Hospital::create(['nombre' => 'Hospital Rezola Cañete', 'tipo' => 'MINSA', 'alias' => 'MINSA - HOSPITAL REZOLA CAÑETE', 'clase' => 'II-2', 'prioridad' => 'A']);
		$r->peaple()->sync([9, 19, 100]);
		$r = Hospital::create(['nombre' => 'Hospital San José del Callao', 'tipo' => 'MINSA', 'alias' => 'MINSA - HOSPITAL SAN JOSE', 'clase' => 'II-2', 'prioridad' => 'A']);
		$r->peaple()->sync([13, 28, 43, 63, 67, 69, 84, 92, 96, 97, 101, 102, 132]);
		$r = Hospital::create(['nombre' => 'Hospital Santa Rosa', 'tipo' => 'MINSA', 'alias' => 'MINSA - HOSPTITAL SANTA ROSA', 'clase' => 'III-1', 'prioridad' => 'A']);
		$r->peaple()->sync([2, 7, 51, 60, 73, 106, 114, 124]);
		$r = Hospital::create(['nombre' => 'Instituto Nacional de Enfermedades Neoplásicas', 'tipo' => 'MINSA', 'alias' => 'MINSA - INEN - ENFERMEDADES NEOPLÁSICAS', 'clase' => 'III-2', 'prioridad' => 'A']);
		$r->peaple()->sync([1, 4, 5, 14, 32, 34, 36, 72, 80, 125]);
		$r = Hospital::create(['nombre' => 'Instituto Nacional de Salud del Niño', 'tipo' => 'MINSA', 'alias' => 'MINSA - INSN BREÑA - SALUD DEL NIÑO', 'clase' => 'III-2', 'prioridad' => 'A']);
		$r->peaple()->sync([2, 7, 51, 60, 73, 106, 114, 124]);
		$r = Hospital::create(['nombre' => 'Instituto Nacional de Salud del Niño San Borja', 'tipo' => 'MINSA', 'alias' => 'MINSA - INSN SAN BORJA - SALUD DEL NIÑO', 'clase' => 'III-2', 'prioridad' => 'A']);
		$r->peaple()->sync([8, 23, 26, 74, 82, 89, 113, 118, 127]);
		$r = Hospital::create(['nombre' => 'Hospital de Emergencias José Casimiro Ulloa', 'tipo' => 'MINSA', 'alias' => 'MINSA - JOSÉ CASIMIRO ULLOA', 'clase' => 'III-1', 'prioridad' => 'A']);
		$r->peaple()->sync([1, 4, 5, 14, 32, 34, 36, 72, 80, 125]);
		$r = Hospital::create(['nombre' => 'Hospital María Auxiliadora', 'tipo' => 'MINSA', 'alias' => 'MINSA - MARIA AUXILIADORA', 'clase' => 'III-1', 'prioridad' => 'A']);
		$r->peaple()->sync([10, 11, 17, 24, 33, 39, 54, 55, 57, 62, 66, 77, 79, 81, 85, 90, 107, 109, 128, 129, 131, 133]);
		$r = Hospital::create(['nombre' => 'Instituto Nacional de Ciencias Neurológicas', 'tipo' => 'MINSA', 'alias' => 'MINSA - MOGROVEJO', 'clase' => 'III-2', 'prioridad' => 'A']);
		$r->peaple()->sync([8, 23, 26, 74, 82, 89, 113, 118, 127]);
		$r = Hospital::create(['nombre' => 'Hospital San Juan de Lurigancho', 'tipo' => 'MINSA', 'alias' => 'MINSA - SAN JUAN DE LURIGANCHO', 'clase' => 'II-2', 'prioridad' => 'A']);
		$r->peaple()->sync([12, 15, 18, 31, 35, 46, 58, 68, 88, 98, 111, 115, 120]);
		$r = Hospital::create(['nombre' => 'Hospital Nacional Sergio E. Bernales', 'tipo' => 'MINSA', 'alias' => 'MINSA - SERGIO E. BERNALES', 'clase' => 'III-1', 'prioridad' => 'A']);
		$r->peaple()->sync([6, 16, 42, 48, 49, 56, 61, 75, 87, 91, 104, 105, 108, 112, 121, 122]);
		$r = Hospital::create(['nombre' => 'Instituto Nacional Materno Perinatal', 'tipo' => 'MINSA', 'alias' => 'MINSA- INMP - MATERNO PERINATAL', 'clase' => 'III-2', 'prioridad' => 'A']);
		$r->peaple()->sync([12, 15, 18, 31, 35, 46, 58, 68, 88, 98, 111, 115, 120]);
		$r = Hospital::create(['nombre' => 'Hospital Centro Médico Naval', 'tipo' => 'MINSA', 'alias' => 'NAVAL - HOSPITAL CENTRO MEDICO NAVAL', 'clase' => 'III-1', 'prioridad' => 'B']);
		$r->peaple()->sync([28, 84, 92]);
		$r = Hospital::create(['nombre' => 'Hospital Central Policia Nacional Del Perú', 'tipo' => 'PNP', 'alias' => 'PNP- HOSPTITAL CENTRAL POLICIA NACIONAL DEL PERU', 'clase' => 'III-1', 'prioridad' => 'B']);
		$r->peaple()->sync([7, 114]);
		$r = Hospital::create(['nombre' => 'Hospital I Aurelio Díaz Ufano y Peral', 'tipo' => 'ESSALUD', 'alias' => 'ESSALUD - HOSPITAL AURELIO DIAZ UFANO', 'clase' => 'II-1', 'prioridad' => 'B']);
		$r->peaple()->sync([8, 88, 98]);
		$r = Hospital::create(['nombre' => 'Hospital Vitarte', 'tipo' => 'MINSA', 'alias' => 'MINSA - HOSPITAL VITARTE', 'clase' => 'II-1', 'prioridad' => 'B']);
		$r->peaple()->sync([25, 35]);
		$r = Hospital::create(['nombre' => 'Clínica Centenario Peruano Japonesa', 'tipo' => 'CLINICA', 'alias' => 'CLINICA - CENTENARIO PERUANO JAPONES', 'clase' => '-', 'prioridad' => 'B']);
		$r->peaple()->sync([7, 76]);
		$r = Hospital::create(['nombre' => 'Hospital José Agurto Tello de Chosica', 'tipo' => 'MINSA', 'alias' => 'MINSA - HOSPITAL JOSE AGURTO TELLO', 'clase' => 'II-2', 'prioridad' => 'A']);
		// $r->peaple()->sync([]);
		$r = Hospital::create(['nombre' => 'Hospital Barranca Cajatambo', 'tipo' => 'MINSA', 'alias' => 'MINSA - HOSPITAL BARRANCA CAJATAMBO', 'clase' => 'II-2', 'prioridad' => 'A']);
		// $r->peaple()->sync([]);
		$r = Hospital::create(['nombre' => 'Hospital de Supe “Laura Esther Rodriguez Dulanto”', 'tipo' => 'MINSA', 'alias' => 'MINSA - HOSPITAL SUPE - LAURA ESTHER RODRIGUEZ DULANTO', 'clase' => 'II-1', 'prioridad' => 'B']);
		// $r->peaple()->sync([]);
		$r = Hospital::create(['nombre' => 'Hospital de Emergencias San Juan De Matucana', 'tipo' => 'MINSA', 'alias' => 'MINSA - HOSPITAL DE EMERGENCIAS SAN JUAN DE MATUCANA', 'clase' => 'II-1', 'prioridad' => 'B']);
		// $r->peaple()->sync([]);
    }
}